nan = input("请输入你的数字:")
nan = int(nan)
nan2 = input("请输入你的数字:")
nan2 = int(nan2)
nan3 = input("请输入你的数字:")
nan3 = int(nan3)
nan4 = input("请输入你的数字:")
nan4 = int(nan4)
nan5 = input("请输入你的数字:")
nan5 = int(nan5)
nan6 = input("请输入你的数字:")
nan6 = int(nan6)
nan7 = input("请输入你的数字:")
nan7 = int(nan7)
nan8 = input("请输入你的数字:")
nan8 = int(nan8)
nan9 = input("请输入你的数字:")
nan9 = int(nan9)
nan10 = input("请输入你的数字:")
nan10 = int(nan10)

print("数字总和是：", (nan+nan2+nan3+nan4+nan5+nan6+nan7+nan8+nan9+nan10))
print("平均值：", (nan+nan2+nan3+nan4+nan5+nan6+nan7+nan8+nan9+nan10)/10)